spring.application.name=langchain4j-demo
server.port=8000

# ==========================================
# Configuración de Groq (LangChain4j)
# ==========================================
langchain4j.open-ai.chat-model.api-key=${GROQ_API_KEY}
langchain4j.open-ai.chat-model.base-url=${GROQ_BASE_URL:https://api.groq.com/openai/v1}
langchain4j.open-ai.chat-model.model-name=${GROQ_MODEL_NAME}

# ==========================================
# Configuración de Base de Datos PostgreSQL (Local)
# ==========================================
spring.datasource.url=jdbc:postgresql://postgres:5432/langchain4j_demo
  #  en local # localhost:5433 #
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ==========================================
# Configuración de Hibernate / JPA
# ==========================================
# 'update' creará la tabla 'chat_mensajes' automáticamente al iniciar si no existe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect